import { defineConfig } from 'oxlint';

/**
 * Type-aware rules require `oxlint-tsgolint` and `options.typeAware: true` on the
 * consumer's root `oxlint.config.js` (not on this export alone).
 */
const typescriptConfig = defineConfig({
  overrides: [
    {
      files: ['**/*.ts', '**/*.mts', '**/*.tsx'],
      plugins: ['typescript'],
      rules: {
        'no-unused-vars': [
          'error',
          {
            args: 'all',
            argsIgnorePattern: '^_',
            caughtErrors: 'all',
            caughtErrorsIgnorePattern: '^_',
            destructuredArrayIgnorePattern: '^_',
            varsIgnorePattern: '^_',
            ignoreRestSiblings: true,
          },
        ],
        'no-throw-literal': 'off',
        'prefer-promise-reject-errors': 'off',
        'require-await': 'off',
        'no-empty-function': 'error',
        'init-declarations': ['off', 'always'],
        'no-dupe-class-members': 'error',
        'no-redeclare': 'off',
        'prefer-destructuring': 'off',
        // this plugin is busted in oxc
        // 'typescript-sort-keys/interface': [
        //   'error',
        //   'asc',
        //   {
        //     caseSensitive: true,
        //     natural: false,
        //     requiredFirst: false,
        //   },
        // ],
        'max-params': 'off',
        'no-magic-numbers': 'off',
        'no-restricted-imports': [
          'error',
          {
            paths: [],
          },
        ],
        'typescript/await-thenable': 'error',
        'typescript/ban-ts-comment': 'off',
        'typescript/no-array-delete': 'error',
        'typescript/no-base-to-string': 'error',
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'error',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-floating-promises': 'off',
        'typescript/no-for-in-array': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-misused-promises': [
          'error',
          {
            checksVoidReturn: false,
          },
        ],
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-redundant-type-constituents': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': [
          'error',
          {
            allowAny: false,
            allowBoolean: false,
            allowNullish: false,
            allowNumberAndString: false,
            allowRegExp: false,
          },
        ],
        'typescript/restrict-template-expressions': [
          'error',
          {
            allowNumber: true,
          },
        ],
        'typescript/triple-slash-reference': 'error',
        'typescript/unbound-method': 'error',
        'typescript/adjacent-overload-signatures': 'error',
        'typescript/array-type': 'error',
        'typescript/ban-tslint-comment': 'error',
        'typescript/class-literal-property-style': 'error',
        'typescript/consistent-generic-constructors': 'error',
        'typescript/consistent-indexed-object-style': 'error',
        'typescript/consistent-type-assertions': 'error',
        'typescript/consistent-type-definitions': 'off',
        'typescript/no-confusing-non-null-assertion': 'error',
        'typescript/no-inferrable-types': 'error',
        'typescript/non-nullable-type-assertion-style': 'error',
        'typescript/prefer-find': 'error',
        'typescript/prefer-for-of': 'off',
        'typescript/prefer-function-type': 'error',
        'typescript/prefer-includes': 'error',
        'typescript/prefer-nullish-coalescing': 'error',
        'typescript/prefer-regexp-exec': 'off',
        'typescript/prefer-string-starts-ends-with': 'error',
        'typescript/no-confusing-void-expression': 'error',
        'typescript/no-deprecated': 'error',
        'typescript/no-dynamic-delete': 'error',
        'typescript/no-extraneous-class': 'error',
        'typescript/no-invalid-void-type': 'error',
        'typescript/no-meaningless-void-operator': 'error',
        'typescript/no-misused-spread': 'error',
        'typescript/no-mixed-enums': 'error',
        'typescript/no-non-null-asserted-nullish-coalescing': 'error',
        'typescript/no-non-null-assertion': 'off',
        'typescript/no-unnecessary-boolean-literal-compare': 'error',
        'typescript/no-unnecessary-template-expression': 'error',
        'typescript/no-unnecessary-type-arguments': 'error',
        'typescript/no-unnecessary-type-conversion': 'error',
        'typescript/no-unnecessary-type-parameters': 'error',
        'typescript/no-useless-default-assignment': 'error',
        'typescript/prefer-literal-enum-member': 'error',
        'typescript/prefer-reduce-type-parameter': 'error',
        'typescript/prefer-return-this-type': 'error',
        'typescript/related-getter-setter-pairs': 'error',
        'typescript/return-await': 'off',
        'typescript/unified-signatures': 'error',
        'typescript/use-unknown-in-catch-callback-variable': 'error',
        'typescript/consistent-type-exports': 'off',
        'typescript/consistent-type-imports': [
          'error',
          {
            prefer: 'type-imports',
            fixStyle: 'separate-type-imports',
            disallowTypeAnnotations: false,
          },
        ],
        'typescript/explicit-function-return-type': 'off',
        'typescript/explicit-member-accessibility': 'off',
        'typescript/explicit-module-boundary-types': 'error',
        'typescript/no-import-type-side-effects': 'error',
        'typescript/no-unnecessary-qualifier': 'error',
        'typescript/no-useless-empty-export': 'error',
        'typescript/parameter-properties': 'off',
        'typescript/prefer-enum-initializers': 'off',
        'typescript/prefer-readonly': 'off',
        'typescript/prefer-readonly-parameter-types': 'off',
        'typescript/promise-function-async': 'off',
        'typescript/require-array-sort-compare': 'off',
        'typescript/strict-boolean-expressions': 'error',
        'typescript/switch-exhaustiveness-check': [
          'error',
          {
            requireDefaultForNonUnion: true,
          },
        ],
        'typescript/consistent-return': 'error',
        'typescript/dot-notation': 'error',
      },
    },
  ],
});

export default typescriptConfig;
