import { defineConfig } from 'oxlint';

export const eslintRules = defineConfig({
  rules: {
    'array-callback-return': [
      'error',
      {
        allowImplicit: true,
      },
    ],
    'no-await-in-loop': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-constructor-return': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-promise-executor-return': 'error',
    'no-self-compare': 'error',
    'no-template-curly-in-string': 'error',
    'no-unused-private-class-members': 'error',
    'no-use-before-define': 'error',
    'block-scoped-var': 'error',
    'default-case': 'error',
    'default-case-last': 'error',
    'default-param-last': 'error',
    eqeqeq: [
      'error',
      'always',
      {
        null: 'ignore',
      },
    ],
    'func-names': ['error', 'as-needed'],
    'func-style': [
      'error',
      'expression',
      {
        allowArrowFunctions: true,
      },
    ],
    'grouped-accessor-pairs': 'error',
    'guard-for-in': 'error',
    'logical-assignment-operators': [
      'error',
      'always',
      {
        enforceForIfStatements: true,
      },
    ],
    'max-classes-per-file': ['error', 1],
    'max-depth': ['error', 4],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-caller': 'error',
    'no-console': 'warn',
    'no-continue': 'error',
    'no-else-return': [
      'error',
      {
        allowElseIf: false,
      },
    ],
    'no-empty-function': [
      'error',
      {
        allow: ['arrowFunctions'],
      },
    ],
    'no-empty-static-block': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-implicit-coercion': 'error',
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-object-constructor': 'error',
    'no-param-reassign': [
      'error',
      {
        props: false,
      },
    ],
    'no-plusplus': 'error',
    'no-proto': 'error',
    'no-redeclare': 'error',
    'no-restricted-globals': [
      'error',
      {
        name: 'isFinite',
        message: 'Use Number.isFinite instead',
      },
      {
        name: 'isNaN',
        message: 'Use Number.isNaN instead',
      },
      {
        name: 'parseInt',
        message: 'Use Number.parseInt instead',
      },
      {
        name: 'parseFloat',
        message: 'Use Number.parseFloat instead',
      },
      {
        name: 'addEventListener',
        message: 'Use window.addEventListener instead',
      },
      {
        name: 'blur',
        message: 'Use window.blur instead',
      },
      {
        name: 'close',
        message: 'Use window.close instead',
      },
      {
        name: 'closed',
        message: 'Use window.closed instead',
      },
      {
        name: 'confirm',
        message: 'Use window.confirm instead',
      },
      {
        name: 'defaultStatus',
        message: 'Use window.defaultStatus instead',
      },
      {
        name: 'defaultstatus',
        message: 'Use window.defaultstatus instead',
      },
      {
        name: 'event',
        message: 'Use window.event instead',
      },
      {
        name: 'external',
        message: 'Use window.external instead',
      },
      {
        name: 'find',
        message: 'Use window.find instead',
      },
      {
        name: 'focus',
        message: 'Use window.focus instead',
      },
      {
        name: 'frameElement',
        message: 'Use window.frameElement instead',
      },
      {
        name: 'frames',
        message: 'Use window.frames instead',
      },
      {
        name: 'history',
        message: 'Use window.history instead',
      },
      {
        name: 'innerHeight',
        message: 'Use window.innerHeight instead',
      },
      {
        name: 'innerWidth',
        message: 'Use window.innerWidth instead',
      },
      {
        name: 'length',
        message: 'Use window.length instead',
      },
      {
        name: 'location',
        message: 'Use window.location instead',
      },
      {
        name: 'locationbar',
        message: 'Use window.locationbar instead',
      },
      {
        name: 'menubar',
        message: 'Use window.menubar instead',
      },
      {
        name: 'moveBy',
        message: 'Use window.moveBy instead',
      },
      {
        name: 'moveTo',
        message: 'Use window.moveTo instead',
      },
      {
        name: 'name',
        message: 'Use window.name instead',
      },
      {
        name: 'onblur',
        message: 'Use window.onblur instead',
      },
      {
        name: 'onerror',
        message: 'Use window.onerror instead',
      },
      {
        name: 'onfocus',
        message: 'Use window.onfocus instead',
      },
      {
        name: 'onload',
        message: 'Use window.onload instead',
      },
      {
        name: 'onresize',
        message: 'Use window.onresize instead',
      },
      {
        name: 'onunload',
        message: 'Use window.onunload instead',
      },
      {
        name: 'open',
        message: 'Use window.open instead',
      },
      {
        name: 'opener',
        message: 'Use window.opener instead',
      },
      {
        name: 'opera',
        message: 'Use window.opera instead',
      },
      {
        name: 'outerHeight',
        message: 'Use window.outerHeight instead',
      },
      {
        name: 'outerWidth',
        message: 'Use window.outerWidth instead',
      },
      {
        name: 'pageXOffset',
        message: 'Use window.pageXOffset instead',
      },
      {
        name: 'pageYOffset',
        message: 'Use window.pageYOffset instead',
      },
      {
        name: 'parent',
        message: 'Use window.parent instead',
      },
      {
        name: 'print',
        message: 'Use window.print instead',
      },
      {
        name: 'removeEventListener',
        message: 'Use window.removeEventListener instead',
      },
      {
        name: 'resizeBy',
        message: 'Use window.resizeBy instead',
      },
      {
        name: 'resizeTo',
        message: 'Use window.resizeTo instead',
      },
      {
        name: 'screen',
        message: 'Use window.screen instead',
      },
      {
        name: 'screenLeft',
        message: 'Use window.screenLeft instead',
      },
      {
        name: 'screenTop',
        message: 'Use window.screenTop instead',
      },
      {
        name: 'screenX',
        message: 'Use window.screenX instead',
      },
      {
        name: 'screenY',
        message: 'Use window.screenY instead',
      },
      {
        name: 'scroll',
        message: 'Use window.scroll instead',
      },
      {
        name: 'scrollbars',
        message: 'Use window.scrollbars instead',
      },
      {
        name: 'scrollBy',
        message: 'Use window.scrollBy instead',
      },
      {
        name: 'scrollTo',
        message: 'Use window.scrollTo instead',
      },
      {
        name: 'scrollX',
        message: 'Use window.scrollX instead',
      },
      {
        name: 'scrollY',
        message: 'Use window.scrollY instead',
      },
      {
        name: 'status',
        message: 'Use window.status instead',
      },
      {
        name: 'statusbar',
        message: 'Use window.statusbar instead',
      },
      {
        name: 'stop',
        message: 'Use window.stop instead',
      },
      {
        name: 'toolbar',
        message: 'Use window.toolbar instead',
      },
      {
        name: 'top',
        message: 'Use window.top instead',
      },
    ],
    'no-restricted-properties': [
      'error',
      {
        object: 'arguments',
        property: 'callee',
        message: 'arguments.callee is deprecated',
      },
      {
        object: 'global',
        property: 'isFinite',
        message: 'Please use Number.isFinite instead',
      },
      {
        object: 'self',
        property: 'isFinite',
        message: 'Please use Number.isFinite instead',
      },
      {
        object: 'window',
        property: 'isFinite',
        message: 'Please use Number.isFinite instead',
      },
      {
        object: 'global',
        property: 'isNaN',
        message: 'Please use Number.isNaN instead',
      },
      {
        object: 'self',
        property: 'isNaN',
        message: 'Please use Number.isNaN instead',
      },
      {
        object: 'window',
        property: 'isNaN',
        message: 'Please use Number.isNaN instead',
      },
      {
        property: '__defineGetter__',
        message: 'Please use Object.defineProperty instead.',
      },
      {
        property: '__defineSetter__',
        message: 'Please use Object.defineProperty instead.',
      },
    ],
    'no-return-assign': ['error', 'always'],
    'no-script-url': 'error',
    'no-sequences': 'error',
    'no-shadow': 'error',
    'no-throw-literal': 'error',
    'no-unneeded-ternary': [
      'error',
      {
        defaultAssignment: false,
      },
    ],
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'object-shorthand': ['error', 'always'],
    'operator-assignment': ['error', 'always'],
    'prefer-const': [
      'error',
      {
        ignoreReadBeforeAssign: true,
      },
    ],
    'prefer-destructuring': 'error',
    'prefer-exponentiation-operator': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-object-has-own': 'error',
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': [
      'error',
      {
        disallowRedundantWrapping: true,
      },
    ],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    radix: 'error',
    'require-await': 'error',
    'symbol-description': 'error',
    'vars-on-top': 'error',
    yoda: 'error',
    'unicode-bom': ['error', 'never'],
    'sort-keys': 'error',
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-vars': 'error',
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
  },
});
